var roles = {
	abaddon: {},
	alchemist: {},
	ancient_apparition: {},
	antimage: { rightclick: true },
	arc_warden: {},
	axe: { disable: true },
	bane: {},
	batrider: { magic: true },
	beastmaster: {},
	bloodseeker: {},
	bounty_hunter: {},
	brewmaster: {},
	bristleback: {},
	broodmother: {},
	centaur: {},
	chaos_knight: {},
	chen: {},
	clinkz: {},
	clockwerk: {},
	crystal_maiden: {},
	dark_seer: {},
	dazzle: {},
	death_prophet: {},
	disruptor: {},
	doom: {},
	dragon_knight: {},
	drow_ranger: {},
	earth_spirit: {},
	earthshaker: {},
	elder_titan: {},
	ember_spirit: {},
	enchantress: {},
	enigma: {},
	faceless_void: {},
	gyrocopter: {},
	huskar: {},
	invoker: {},
	jakiro: {},
	juggernaut: {},
	keeper_of_the_light: {},
	kunkka: {},
	legion_commander: {},
	leshrac: {},
	lich: {},
	lifestealer: {},
	lina: {},
	lion: {},
	lone_druid: {},
	luna: {},
	lycan: {},
	magnus: {},
	medusa: {},
	meepo: {},
	mirana: {},
	morphling: {},
	naga_siren: {},
	natures_prophet: {},
	necrophos: {},
	night_stalker: {},
	nyx_assassin: {},
	ogre_magi: {},
	omniknight: {},
	oracle: {},
	outworld_devourer: {},
	phantom_assassin: {},
	phantom_lancer: {},
	phoenix: {},
	puck: {},
	pudge: {},
	pugna: {},
	queenofpain: {},
	razor: {},
	riki: {},
	rubick: {},
	sand_king: {},
	shadow_demon: {},
	shadow_fiend: {},
	shadow_shaman: {},
	silencer: {},
	skywrath_mage: {},
	slardar: {},
	slark: {},
	sniper: {},
	spectre: {},
	spirit_breaker: {},
	storm_spirit: {},
	sven: {},
	techies: {},
	templar_assassin: {},
	terrorblade: {},
	tidehunter: {},
	timbersaw: {},
	tinker: {},
	tiny: {},
	treant: {},
	troll_warlord: {},
	tusk: {},
	undying: {},
	ursa: {},
	vengeful_spirit: {},
	venomancer: {},
	viper: {},
	visage: {},
	warlock: {},
	weaver: {},
	windrunner: {},
	winter_wyvern: {},
	wisp: {},
	witch_doctor: {},
	wraith_king: {},
	zeus: {}
};

function showHeroes (value) {
	for (var prop in roles) {
		if (roles.hasOwnProperty(prop)) {
			var img = document.getElementById(prop);
			if (value === "none" || roles[prop].hasOwnProperty(value))
				img.classList.remove("invis");
			else
				img.classList.add("invis");
		}
	}
}